export const NODE_DETAILS = {
  spec: {
    label: 'Spec',
    role: 'Source of truth',
    color: '#F1EFE8',
    border: '#5F5E5A',
    text: '#2C2C2A',
    details: [
      'Engineer pastes a brief; the compiler turns it into a typed, schema-validated spec.',
      'Validator gates it: no acceptance criteria, no plan — incomplete specs never reach generation.',
      'Consistency gate checks against the existing codebase — catches conflicts before any code runs.',
      'Human approves the spec; it becomes the versioned audit trail everything traces back to.',
      'One spec = one feature = one PR — batch discipline enforced upstream.',
    ],
  },
  router: {
    label: 'Risk Router',
    role: 'Tier assignment',
    color: '#FAEEDA',
    border: '#854F0B',
    text: '#412402',
    details: [
      'Reads the spec before anything runs and assigns a risk tier.',
      'High-risk signals: auth, payments, PHI, schema migrations, public API surface.',
      'High-risk → hardened harness, security + compliance workers, mandatory human gates.',
      'Low-risk CRUD → fast lane, fewer gates, auto-approve eligible.',
      'This is how the trust ladder collapses selectively — autonomy expands for low-risk without removing safeguards from high-risk.',
    ],
  },
  orchestration: {
    label: 'Orchestration',
    role: 'Deterministic conductor',
    color: '#E1F5EE',
    border: '#0F6E56',
    text: '#04342C',
    details: [
      'Deterministic code, not a model — a DAG, not a swarm.',
      'Spec compiles into ordered stages: migrate → api → frontend → tests (config in parallel).',
      'Each stage passes an eval gate before feeding the next.',
      'Typed artifacts between stages — frontend gets a typed API contract, not prose.',
      'Failure recovery: per-stage bounded retries, then human escalation with checkpointing.',
    ],
  },
  workers: {
    label: 'Workers',
    role: 'Same model, six harnesses',
    color: '#E1F5EE',
    border: '#0F6E56',
    text: '#04342C',
    details: [
      'Same underlying model everywhere — the model is a swappable commodity.',
      'Build harness — constructs artifacts per pattern (CRUD+UI, Integration, Workflow, Analytics).',
      'Migration harness — per DB engine (Postgres, MongoDB, DynamoDB, Redis); rollback-safe, zero-downtime enforced.',
      'Integration harness — external APIs, retry/backoff, idempotency keys non-optional.',
      'Security worker — adversarial, read-only; finds vulnerabilities in what build produced.',
      'Compliance worker — confirms required controls are present: audit, Vault, permission gates, PHI classification.',
      'Performance harness — adversarial to latency; finds N+1 queries and missing indexes.',
    ],
  },
  verification: {
    label: 'Verification',
    role: 'Defense in depth',
    color: '#E1F5EE',
    border: '#0F6E56',
    text: '#04342C',
    details: [
      'Woven in per-stage, not bolted on at the end.',
      'Cheap checks first: compile, lint, typecheck.',
      'Pattern conformance: LLM judge + static checks against the retrieved exemplar.',
      'Security and compliance workers run before CI.',
      'Spec-derived tests generated from acceptance criteria, independent of implementation.',
      'Real CI runs in the loop before the PR emits.',
      'Human QA gate: risk-weighted, live environment, signs off on acceptance criteria.',
    ],
  },
  review: {
    label: 'Review',
    role: 'Human-in-the-loop',
    color: '#E1F5EE',
    border: '#0F6E56',
    text: '#04342C',
    details: [
      'Progressive disclosure — engineers intervene at every stage, not just the end.',
      'High-risk output gets a red-team pass and mandatory human review.',
      'PR carries full provenance: every file traces to a spec field and named approver.',
      'Clean diff + generation report: what was produced, why, and what exemplars were matched.',
      'Trust ladder: as pass rates prove reliability, gates collapse — never on a schedule, always on evidence.',
    ],
  },
  pr: {
    label: 'PR',
    role: 'Deployable output',
    color: '#F1EFE8',
    border: '#5F5E5A',
    text: '#2C2C2A',
    details: [
      'A reviewable, deployable pull request across the full stack.',
      'Every file links to its spec field — the generation report is the audit trail.',
      'Passes CI on first run 80% of the time.',
      'Requires ≤30 minutes of human cleanup — more than that is a factory failure.',
      'Spec + traces + generation report satisfies SOC 2 CC8.1 and HIPAA §164.312(b).',
    ],
  },
  intel: {
    label: 'Codebase Intelligence',
    role: 'Context engine',
    color: '#EEEDFE',
    border: '#534AB7',
    text: '#26215C',
    details: [
      'Indexes seven repos across three languages, four DB engines, two frontend frameworks.',
      'Four stores: structural index, exemplar store, architectural facts, product profile.',
      'Exemplar store: canonical implementation of each pattern per repo — why output reads native.',
      'Hybrid retrieval: semantic + structural graph + exemplar lookup feeds context to workers.',
      'Stays current via re-index on merge and exemplars graduated by the learning loop.',
    ],
  },
  learn: {
    label: 'Learning Loop',
    role: 'Self-improvement flywheel',
    color: '#EEEDFE',
    border: '#534AB7',
    text: '#26215C',
    details: [
      'Every run is traced (OpenTelemetry-style spans on every tool call).',
      'Every deploy emits the four DORA outcomes — the factory continuously reproduces the time study.',
      'Repeated failures become guardrails and new skills.',
      'Accepted work sharpens the exemplars retrieval serves.',
      'Factory improves without touching the model — improvement lives in the harness, not the weights.',
    ],
  },
  security: {
    label: 'Security Worker',
    role: 'Adversarial reviewer',
    color: '#EEEDFE',
    border: '#534AB7',
    text: '#26215C',
    details: [
      'Adversarial posture, read-only tools — success = finding vulnerabilities, not validating that things work.',
      'Runs independently of build workers — no bias toward approving its own output.',
      'Context: OWASP top 10, Athena compliance controls (HIPAA/SOC 2), known attack patterns as exemplars.',
      'Checks: permission gates on every endpoint, no credential leaks, no injection surfaces.',
      'A finding blocks the PR; no finding is a pass — the inverse of a build worker\'s success criterion.',
    ],
  },
  comply: {
    label: 'Compliance Worker',
    role: 'Controls verifier',
    color: '#EEEDFE',
    border: '#534AB7',
    text: '#26215C',
    details: [
      'Distinct from security: security finds what\'s broken, compliance confirms what\'s required is present.',
      'Checks: audit logging wired on every mutation, Vault refs used (never raw credentials), permission gate on every endpoint.',
      'PHI data classifications correct; change traces to approved spec with named approver.',
      'Mandatory on fintech and healthtech products — SOC 2 CC8.1 and HIPAA §164.312(b).',
      'Passes by confirming the checklist is complete; fails by finding a missing control.',
    ],
  },
};

export const INITIAL_NODES = [
  { id: 'spec',          position: { x: 40,   y: 240 }, data: { id: 'spec' },          type: 'factory' },
  { id: 'router',        position: { x: 220,  y: 240 }, data: { id: 'router' },         type: 'factory' },
  { id: 'orchestration', position: { x: 420,  y: 240 }, data: { id: 'orchestration' },  type: 'factory' },
  { id: 'workers',       position: { x: 640,  y: 240 }, data: { id: 'workers' },         type: 'factory' },
  { id: 'verification',  position: { x: 860,  y: 240 }, data: { id: 'verification' },    type: 'factory' },
  { id: 'review',        position: { x: 1080, y: 240 }, data: { id: 'review' },          type: 'factory' },
  { id: 'pr',            position: { x: 1300, y: 240 }, data: { id: 'pr' },              type: 'factory' },
  { id: 'intel',         position: { x: 530,  y: 60  }, data: { id: 'intel' },           type: 'factory' },
  { id: 'learn',         position: { x: 530,  y: 420 }, data: { id: 'learn' },           type: 'factory' },
  { id: 'security',      position: { x: 780,  y: 420 }, data: { id: 'security' },        type: 'factory' },
  { id: 'comply',        position: { x: 980,  y: 420 }, data: { id: 'comply' },          type: 'factory' },
];

export const INITIAL_EDGES = [
  { id: 'e-spec-router',     source: 'spec',         target: 'router',        animated: false, style: { stroke: '#0F6E56', strokeWidth: 2 } },
  { id: 'e-router-orch',     source: 'router',       target: 'orchestration', animated: false, style: { stroke: '#0F6E56', strokeWidth: 2 } },
  { id: 'e-orch-workers',    source: 'orchestration',target: 'workers',       animated: false, style: { stroke: '#0F6E56', strokeWidth: 2 } },
  { id: 'e-workers-verify',  source: 'workers',      target: 'verification',  animated: false, style: { stroke: '#0F6E56', strokeWidth: 2 } },
  { id: 'e-verify-review',   source: 'verification', target: 'review',        animated: false, style: { stroke: '#0F6E56', strokeWidth: 2 } },
  { id: 'e-review-pr',       source: 'review',       target: 'pr',            animated: false, style: { stroke: '#0F6E56', strokeWidth: 2 } },
  { id: 'e-intel-orch',      source: 'intel',        target: 'orchestration', animated: false, style: { stroke: '#534AB7', strokeWidth: 1.5, strokeDasharray: '5 4' }, label: 'context', labelStyle: { fill: '#534AB7', fontSize: 11 }, labelBgStyle: { fill: '#fbfbfa' } },
  { id: 'e-intel-workers',   source: 'intel',        target: 'workers',       animated: false, style: { stroke: '#534AB7', strokeWidth: 1.5, strokeDasharray: '5 4' }, label: 'context', labelStyle: { fill: '#534AB7', fontSize: 11 }, labelBgStyle: { fill: '#fbfbfa' } },
  { id: 'e-router-workers',  source: 'router',       target: 'workers',       animated: false, style: { stroke: '#854F0B', strokeWidth: 1.5, strokeDasharray: '5 4' }, label: 'harness tier', labelStyle: { fill: '#854F0B', fontSize: 11 }, labelBgStyle: { fill: '#fbfbfa' } },
  { id: 'e-verify-learn',    source: 'verification', target: 'learn',         animated: false, style: { stroke: '#534AB7', strokeWidth: 1.5, strokeDasharray: '5 4' }, label: 'traces', labelStyle: { fill: '#534AB7', fontSize: 11 }, labelBgStyle: { fill: '#fbfbfa' } },
  { id: 'e-learn-workers',   source: 'learn',        target: 'workers',       animated: false, style: { stroke: '#534AB7', strokeWidth: 1.5, strokeDasharray: '5 4' }, label: 'skills, memory', labelStyle: { fill: '#534AB7', fontSize: 11 }, labelBgStyle: { fill: '#fbfbfa' } },
  { id: 'e-learn-intel',     source: 'learn',        target: 'intel',         animated: false, style: { stroke: '#534AB7', strokeWidth: 1.5, strokeDasharray: '5 4' }, label: 'exemplars', labelStyle: { fill: '#534AB7', fontSize: 11 }, labelBgStyle: { fill: '#fbfbfa' } },
  { id: 'e-sec-verify',      source: 'security',     target: 'verification',  animated: false, style: { stroke: '#534AB7', strokeWidth: 1.5, strokeDasharray: '5 4' }, label: 'adversarial pass', labelStyle: { fill: '#534AB7', fontSize: 11 }, labelBgStyle: { fill: '#fbfbfa' } },
  { id: 'e-comply-verify',   source: 'comply',       target: 'verification',  animated: false, style: { stroke: '#534AB7', strokeWidth: 1.5, strokeDasharray: '5 4' }, label: 'controls check', labelStyle: { fill: '#534AB7', fontSize: 11 }, labelBgStyle: { fill: '#fbfbfa' } },
];
