// PR assembly: a reviewable pull request with provenance and bidirectional traceability.
import { mkdirSync, writeFileSync, copyFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";

export function writePR(plan, spec, run, outDir) {
  const ci = run.results.tests.gate.ci;
  const L = [];
  L.push("# PR: add " + spec.entity + " management to " + spec.product);
  L.push("");
  L.push("> Generated by the Athena software factory from spec `" + spec.specId + "` via plan `" + plan.planId + "`.");
  L.push("> Regulated repo — the risk router would force mandatory human review and a red-team pass before merge.");
  L.push("");
  L.push("## What & why");
  L.push("Implements the CRUD + UI pattern for `" + spec.entity + "`. Every file traces to a spec field or acceptance criterion.");
  L.push("");
  L.push("## Acceptance criteria (the definition of done)");
  for (const a of spec.acceptance) L.push("- " + a);
  L.push("");
  L.push("## Verification");
  L.push("- **CI in the loop** (product test runner): **" + ci.summary + "** — gate " + (ci.pass ? "green ✓" : "red ✗"));
  for (const id of Object.keys(run.results)) {
    const r = run.results[id];
    const g = (r.gate.checks || []).map((c) => (c.pass ? "✓" : "✗") + " " + c.name).join("; ");
    L.push("- `" + id + "` (attempt " + r.attempts + "): " + g);
  }
  L.push("");
  L.push("## Files & provenance");
  L.push("| File | Stage | Provenance |");
  L.push("|------|-------|------------|");
  for (const id of Object.keys(run.results))
    for (const f of run.results[id].gen.files)
      L.push("| `" + f.path + "` | " + id + " | " + run.results[id].gen.provenance + " |");
  L.push("");
  L.push("## Generation plan (DAG)");
  L.push("```json");
  L.push(JSON.stringify({ planId: plan.planId, stages: plan.stages, requiresHumanApprovalBefore: plan.requiresHumanApprovalBefore }, null, 2));
  L.push("```");

  mkdirSync(outDir, { recursive: true });
  const prPath = join(outDir, "PR.md");
  writeFileSync(prPath, L.join("\n") + "\n");
  copyTree(run.workspace, join(outDir, "files"));
  return prPath;
}

function copyTree(src, dst) {
  for (const name of readdirSync(src)) {
    const s = join(src, name), d = join(dst, name);
    if (statSync(s).isDirectory()) copyTree(s, d);
    else { mkdirSync(dirname(d), { recursive: true }); copyFileSync(s, d); }
  }
}
