// Skills: packaged, reusable units of CRUD generation. Each takes the spec + harness
// and emits files (+ a typed artifact for downstream stages) + provenance.
// Faults are injectable to demonstrate the gate catching bad output (see run.mjs flags).

const camel = (s) => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
const titleCase = (s) => s.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
const sqlType = (f) => (f.kind === "enum" ? f.name + "_type" : ({ string: "text", boolean: "boolean", integer: "integer" }[f.kind] || "text"));

function faulted(stage, harness) {
  const f = harness.faults || {};
  return (f.fail && f.fail.has(stage)) || (f.flaky && f.flaky.has(stage) && harness.attempt === 1);
}

export const skills = {
  migrate(spec, harness) {
    const enums = spec.fields.filter((f) => f.kind === "enum")
      .map((f) => "CREATE TYPE " + f.name + "_type AS ENUM (" + f.values.map((v) => "'" + v + "'").join(", ") + ");");
    const cols = [
      "  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),",
      "  merchant_id uuid NOT NULL REFERENCES merchants(id),",
    ];
    for (const f of spec.fields) {
      const def = f.name === "is_default" ? " DEFAULT false" : "";
      cols.push("  " + f.name.padEnd(11) + " " + sqlType(f) + " NOT NULL" + def + ",");
    }
    cols.push("  created_at  timestamptz NOT NULL DEFAULT now(),");
    cols.push("  updated_at  timestamptz NOT NULL DEFAULT now()");

    const up = ["-- migrate:up", ...enums, "CREATE TABLE " + spec.table + " (", cols.join("\n"), ");"];
    if (spec.fields.find((f) => f.name === "is_default"))
      up.push("CREATE UNIQUE INDEX one_default_per_merchant ON " + spec.table + " (merchant_id) WHERE is_default;");
    const down = ["", "-- migrate:down", "DROP TABLE IF EXISTS " + spec.table + ";",
      ...spec.fields.filter((f) => f.kind === "enum").map((f) => "DROP TYPE IF EXISTS " + f.name + "_type;")];

    // FAULT: forget the reversible down migration -> security-floor gate rejects it.
    const content = faulted("migrate", harness) ? up.join("\n") + "\n" : up.join("\n") + "\n" + down.join("\n") + "\n";
    return {
      files: [{ path: "migrations/001_create_" + spec.table + ".sql", content }],
      artifact: { table: spec.table },
      provenance: "matched " + harness.exemplar.path + " (canonical migration shape; unique-default as a partial index)",
    };
  },

  api(spec, harness) {
    const keys = spec.fields.map((f) => camel(f.name));
    // FAULT: forget to clear the previous default -> compiles & passes lint, but the
    // spec-derived CI test for "exactly one default" fails. The "compiles vs correct" gap.
    const clearDefault = faulted("api", harness)
      ? "      // FAULT: forgot to clear the previous default"
      : "      if (row.isDefault) repo.clearDefault(ctx.merchantId);";
    const L = [
      "// generated by factory · " + spec.specId,
      "export const PERMISSION = " + JSON.stringify(spec.permissions) + ";",
      "const KEYS = " + JSON.stringify(keys) + ";",
      'function requirePerm(ctx) { if (!ctx || !Array.isArray(ctx.permissions) || !ctx.permissions.includes(PERMISSION)) { const e = new Error("forbidden"); e.status = 403; throw e; } }',
      "function pick(input) { const o = {}; for (const k of KEYS) { if (input && input[k] !== undefined) o[k] = input[k]; } return o; }",
      "export function create" + spec.entity + "Service(repo, opts) {",
      "  const audit = !!(opts && opts.audit);",
      "  return {",
      "    list(ctx) { requirePerm(ctx); return repo.all(ctx.merchantId); },",
      "    get(ctx, id) { requirePerm(ctx); return repo.get(id); },",
      "    create(ctx, input) {",
      "      requirePerm(ctx);",
      "      const row = Object.assign({ id: repo.nextId(), merchantId: ctx.merchantId, createdAt: repo.now() }, pick(input));",
      clearDefault,
      "      repo.insert(row);",
      '      if (audit) repo.audit(ctx, "create", null, row);',
      "      return row;",
      "    },",
      "    update(ctx, id, patch) {",
      "      requirePerm(ctx);",
      '      const cur = repo.get(id); if (!cur) { const e = new Error("not found"); e.status = 404; throw e; }',
      "      const next = Object.assign({}, cur, pick(patch));",
      "      if (next.isDefault && !cur.isDefault) repo.clearDefault(ctx.merchantId);",
      "      repo.update(next);",
      '      if (audit) repo.audit(ctx, "update", cur, next);',
      "      return next;",
      "    },",
      "    remove(ctx, id) {",
      "      requirePerm(ctx);",
      "      const cur = repo.get(id); if (!cur) return;",
      "      repo.delete(id);",
      "      if (cur.isDefault) {",
      "        const rest = repo.all(ctx.merchantId).slice().sort((a, b) => a.createdAt - b.createdAt);",
      "        if (rest[0]) { rest[0].isDefault = true; repo.update(rest[0]); }",
      "      }",
      '      if (audit) repo.audit(ctx, "delete", cur, null);',
      "    },",
      "    setDefault(ctx, id) {",
      "      requirePerm(ctx);",
      "      repo.clearDefault(ctx.merchantId);",
      '      const cur = repo.get(id); if (!cur) { const e = new Error("not found"); e.status = 404; throw e; }',
      "      cur.isDefault = true; repo.update(cur);",
      "      return cur;",
      "    },",
      "  };",
      "}",
    ];
    const columns = spec.fields.filter((f) => !f.sensitive).map((f) => f.name);
    return {
      files: [{ path: "src/" + spec.table + "/service.mjs", content: L.join("\n") + "\n" }],
      artifact: { contract: { entity: spec.entity, permission: spec.permissions, columns, endpoints: ["list", "get", "create", "update", "remove", "setDefault"] } },
      provenance: "matched " + harness.exemplar.path + " · permission gate + audit mixin from product profile",
    };
  },

  frontend(spec, harness) {
    const contract = harness.upstream.api.gen.artifact.contract; // typed handoff, not prose
    const colLines = contract.columns.map((c) => '  { key: "' + camel(c) + '", header: "' + titleCase(c) + '" },').join("\n");
    const L = [
      "// generated by factory · " + spec.specId,
      "// consumes the typed api-contract artifact from the api stage",
      'import { DataTable } from "../../components/DataTable";',
      'import { use' + spec.entity + 's, PERMISSION } from "./hooks";',
      "",
      "const columns = [",
      colLines,
      "];",
      "",
      "export function " + spec.entity + "List({ can }) {",
      "  if (!can(PERMISSION)) return null;",
      "  const { rows } = use" + spec.entity + "s();",
      "  return <DataTable columns={columns} rows={rows} sortable filterable />;",
      "}",
    ];
    return {
      files: [{ path: "src/" + spec.table + "/" + spec.entity + "List.tsx", content: L.join("\n") + "\n" }],
      provenance: "matched " + harness.exemplar.path + " · consumed api contract columns [" + contract.columns.join(", ") + "]",
    };
  },

  tests(spec, harness) {
    const sensitive = spec.fields.find((f) => f.sensitive);
    const sref = sensitive ? camel(sensitive.name) : null;
    const has = (frag) => spec.acceptance.some((a) => a.includes(frag));
    const L = [
      "// generated by factory · spec-derived (from acceptance criteria, independent of the implementation)",
      'import test from "node:test";',
      'import assert from "node:assert/strict";',
      'import { create' + spec.entity + 'Service, PERMISSION } from "./service.mjs";',
      "",
      "function makeRepo() {",
      "  let id = 0, clock = 0; const rows = new Map(); const auditLog = [];",
      "  return {",
      "    all: (m) => [...rows.values()].filter((r) => r.merchantId === m),",
      "    get: (i) => rows.get(i), insert: (r) => rows.set(r.id, r), update: (r) => rows.set(r.id, r), delete: (i) => rows.delete(i),",
      "    clearDefault: (m) => { for (const r of rows.values()) if (r.merchantId === m) r.isDefault = false; },",
      "    nextId: () => String(++id), now: () => ++clock,",
      '    audit: (ctx, a) => auditLog.push({ actor: ctx.actor, action: a }), auditLog,',
      "  };",
      "}",
      'const ok = { merchantId: "m1", actor: "u1", permissions: [PERMISSION] };',
      'const noPerm = { merchantId: "m1", actor: "u2", permissions: [] };',
      "",
    ];
    if (has("default per merchant")) L.push(
      'test("exactly one default per merchant", () => {',
      "  const s = create" + spec.entity + "Service((repo = makeRepo()), { audit: true });",
      '  s.create(ok, { type: "ach", label: "A", isDefault: true, vaultRef: "v1" });',
      '  s.create(ok, { type: "wire", label: "B", isDefault: true, vaultRef: "v2" });',
      '  const defaults = repo.all("m1").filter((r) => r.isDefault);',
      "  assert.equal(defaults.length, 1);",
      '  assert.equal(defaults[0].label, "B");',
      "});", "");
    if (has("promotes the next")) L.push(
      'test("deleting the default promotes the next by created_at", () => {',
      "  const s = create" + spec.entity + "Service((repo = makeRepo()), { audit: true });",
      '  const a = s.create(ok, { type: "ach", label: "A", isDefault: true, vaultRef: "v1" });',
      '  s.create(ok, { type: "wire", label: "B", isDefault: false, vaultRef: "v2" });',
      "  s.remove(ok, a.id);",
      '  assert.equal(repo.all("m1").find((r) => r.label === "B").isDefault, true);',
      "});", "");
    if (has("audit entry")) L.push(
      'test("every change writes an audit entry", () => {',
      "  const s = create" + spec.entity + "Service((repo = makeRepo()), { audit: true });",
      '  const a = s.create(ok, { type: "ach", label: "A", isDefault: false, vaultRef: "v1" });',
      '  s.update(ok, a.id, { label: "A2" });',
      "  s.remove(ok, a.id);",
      '  assert.deepEqual(repo.auditLog.map((e) => e.action), ["create", "update", "delete"]);',
      "});", "");
    if (has("403")) L.push(
      'test("non-permitted user gets 403", () => {',
      "  const s = create" + spec.entity + "Service((repo = makeRepo()), { audit: true });",
      "  assert.throws(() => s.list(noPerm), (e) => e.status === 403);",
      '  assert.throws(() => s.create(noPerm, { type: "ach", label: "X", vaultRef: "v" }), (e) => e.status === 403);',
      "});", "");
    if (sref && has("reference only")) L.push(
      'test("' + sensitive.name + ' stored as reference only; raw credentials dropped", () => {',
      "  const s = create" + spec.entity + "Service((repo = makeRepo()), { audit: true });",
      '  const r = s.create(ok, { type: "ach", label: "A", isDefault: false, ' + sref + ': "vault://abc", credential: "4111111111111111" });',
      '  assert.equal(r.' + sref + ', "vault://abc");',
      '  assert.equal("credential" in repo.get(r.id), false);',
      "});", "");
    return {
      files: [{ path: "src/" + spec.table + "/service.test.mjs", content: "let repo;\n" + L.join("\n") + "\n" }],
      provenance: "derived from " + spec.specId + " acceptance criteria (" + spec.acceptance.length + " criteria)",
    };
  },

  config(spec, harness) {
    const L = [
      "# generated by factory · " + spec.specId,
      "flag: " + spec.table + "_management",
      "  default: false        # ships dark, flipped per environment",
      "permission: " + spec.permissions,
      "  roles: [merchant_admin, finance_ops]",
    ];
    return {
      files: [{ path: "config/" + spec.table + ".yaml", content: L.join("\n") + "\n" }],
      provenance: "matched " + harness.exemplar.path + " · flag + permission conventions",
    };
  },
};
